---
- name: Enable the EPEL repo
  shell:
    amazon-linux-extras enable epel

- name: Install EPEL repo
  yum:
    name: epel-release
    state: latest

- name: Install Nginx
  yum:
    name: nginx
    state: latest

- name: Start Nginx service
  systemd:
    name: nginx.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: Create logstash
  shell: |
    curl 127.0.0.1
    curl 127.0.0.1
    curl 127.0.0.1